# Generated by Django 2.1.10 on 2019-07-11 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interior_app', '0002_remove_details_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='Expected_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Locality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Number_of_finished_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Overall_cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
