# Generated by Django 2.1.10 on 2019-07-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interior_app', '0003_auto_20190711_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=0, upload_to='profile_image'),
        ),
    ]
