# Generated by Django 2.1.10 on 2019-07-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interior_app', '0004_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Expected_salary',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Overall_cost',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
