# Generated by Django 2.1.10 on 2019-07-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interior_app', '0005_auto_20190722_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Overall_cost',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
