# Generated by Django 2.1.10 on 2019-07-26 11:07

import Interior_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interior_app', '0006_auto_20190723_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Interior_app.models.get_image_filename, verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='Overall_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Interior_app.Profile'),
        ),
    ]
