# Generated by Django 2.1 on 2020-08-18 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interior_app', '0007_auto_20190726_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(default=None)),
                ('query', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Interior_app.Profile')),
            ],
        ),
    ]
