# Generated by Django 2.1 on 2020-08-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interior_app', '0008_query_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Expected_salary',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='profile_img',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Years_of_experience',
            new_name='years_exp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Locality',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Number_of_finished_projects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Overall_cost',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_gST',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='design_area',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='design_expertise',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
