# Generated by Django 2.1 on 2020-08-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interior_app', '0009_auto_20200824_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='budget',
        ),
        migrations.AddField(
            model_name='profile',
            name='higher_budget',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='lower_budget',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
