# Generated by Django 2.1 on 2020-08-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interior_app', '0010_auto_20200825_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_of_project',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_img',
            field=models.ImageField(blank=True, default=0, upload_to='project_image'),
        ),
    ]
