# Generated by Django 2.1 on 2020-09-16 06:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interior_app', '0013_video_upload_professional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story_upload_professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='')),
                ('timestamp_of_story', models.DateField(default=datetime.date.today)),
                ('post_story', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Interior_app.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='video_upload_professional',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
