# Generated by Django 2.1 on 2020-09-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interior_app', '0015_story_upload_professional_story_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name_of_project',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_img',
        ),
    ]
